changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: "🚀 Features"
      labels:
        - enhancement
        - feature
    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix
    - title: "📦 Dependencies"
      labels:
        - dependencies
    - title: "📝 Documentation"
      labels:
        - documentation
        - docs
    - title: "�� Maintenance"
      labels:
        - maintenance
        - chore
    - title: "Other Changes"
      labels:
        - "*"